'use strict';
// Overworld people: 16x20 frames assembled from a head (hair style) and a
// body (outfit), then palette-swapped. Left-facing frames are mirrored for
// right. Frames per direction: stand, step A, step B.

const HEADS = {
  short: {
    down: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..ohhssssssHho..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....ohhhhhhoo...',
      '...ohhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..ohhsssssHhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  cap: {
    down: [
      '................',
      '.....oooooo.....',
      '....oaaaaaao....',
      '...oaaawwaaao...',
      '...oaaaaaaaaAo..',
      '..oAAAAAAAAAAo..',
      '..ohhssssssHho..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '....oaaaaaao....',
      '...oaaaaaaaao...',
      '...oaaaaaaaaAo..',
      '..oAaaaaaaaaAo..',
      '..ohAAAAAAAAho..',
      '..oHhhhhhhhhHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....oaaaaaao....',
      '...oaawaaaaao...',
      '...oaaaaaaaaAo..',
      '.oAAAAAAaaaaAo..',
      '..ohhssssshhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  spiky: {
    down: [
      '....o..o..o.....',
      '...oho.oho.o.o..',
      '..ohhhohhhohho..',
      '.ohhhhhhhhhhhho.',
      '..ohhhhhhhhhHo..',
      '.ohhhhhhhhhhhHo.',
      '..ohsshsssshHo..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '....o..o..o.....',
      '...oho.oho.o.o..',
      '..ohhhohhhohho..',
      '.ohhhhhhhhhhhho.',
      '..ohhhhhhhhhho..',
      '.ohhhhhhhhhhhHo.',
      '..ohhhhhhhhhHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '.......o..o.....',
      '..o...oho.oho...',
      '.ohoo.ohhhohhho.',
      '..ohhhhhhhhhhho.',
      '.ohhhhhhhhhhHo..',
      '..ohhhhhhhhhhHo.',
      '..ohsssssHhhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  long: {
    down: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '.ohhhhhhhhhhhHo.',
      '.ohhssssssssHHo.',
      '.ohsessssssesHo.',
      '.ohsessssssesHo.',
      '.ohhosssssSoHHo.',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '.ohhhhhhhhhhhHo.',
      '.ohhhhhhhhhhhHo.',
      '.ohhhhhhhhhhhHo.',
      '.ohhhhhhhhhhHHo.',
      '.oHhhhhhhhhhHHo.',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....ohhhhhhoo...',
      '...ohhhhhhhhho..',
      '..ohhhhhhhhhhHo.',
      '..ohhhhhhhhhhHo.',
      '..ohhsssssHhhHo.',
      '..osesssSshhHHo.',
      '..osesssSshhHHo.',
      '...ossssSohhHHo.',
    ],
  },
  nurse: {
    down: [
      '.....oooooo.....',
      '....owwwwwwo....',
      '...owwwrrwwwo...',
      '..ohowwwwwwohho.',
      '.ohhhoooooohhhho',
      '.ohhhhhhhhhhhHo.',
      '..ohhssssssHho..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '.....oooooo.....',
      '....owwwwwwo....',
      '...owwwwwwwwo...',
      '..ohowwwwwwohho.',
      '.ohhhoooooohhhho',
      '.ohhhhhhhhhhhHo.',
      '..ohhhhhhhhhHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '.....oooooo.....',
      '....owwwwwwo....',
      '...owrrwwwwwo...',
      '...owwwwwwwwohho',
      '..ohoooooooohhho',
      '..ohhhhhhhhhhHo.',
      '..ohhsssssHhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  bald: {
    down: [
      '................',
      '.....oooooo.....',
      '...oossssssoo...',
      '..osssssssssSo..',
      '..osssssssssSo..',
      '..ohsssssssshHo.',
      '..ohhoossoohHho.',
      '..ossessssesSo..',
      '..osshhhhhhsSo..',
      '...oshhhhhhSo...',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '...oossssssoo...',
      '..osssssssssSo..',
      '..osssssssssSo..',
      '..ohssssssssHo..',
      '..ohhssssssHHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....osssssSoo...',
      '...osssssssSSo..',
      '..osssssssssSo..',
      '..ossssssshhHo..',
      '..osoosssHhhHo..',
      '..osesssSshHHo..',
      '..oshhhhSshHo...',
      '...ohhhhSSHo....',
    ],
  },
};

const BODIES = {
  tee: {
    down: [[
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..oCccccccccCo..',
      '..osCccccccCso..',
      '..oopppppppppoo.',
      '...opppppppPo...',
      '...oppPooppPo...',
      '...oppPooppPo...',
      '...okkkookkko...',
      '....ooo..ooo....',
    ], [
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..osccccccccCo..',
      '..oCCcccccccso..',
      '..oopppppppppoo.',
      '...opppppppPo...',
      '...oppPooppPo...',
      '...oppPookkko...',
      '...okkko.ooo....',
      '....ooo.........',
    ], [
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..oCccccccccso..',
      '..osccccccCCCo..',
      '..oopppppppppoo.',
      '...opppppppPo...',
      '...oppPooppPo...',
      '...okkkooppPo...',
      '....ooo.okkko...',
      '.........ooo....',
    ]],
    left: [[
      '....ooccccoo....',
      '...occcCCcco....',
      '...occcCCcco....',
      '...occcsscco....',
      '...oopppppoo....',
      '....opppppo.....',
      '....opppPo......',
      '....opppPo......',
      '...okkkkko......',
      '....oooooo......',
    ], [
      '....ooccccoo....',
      '...occCCccco....',
      '...occCCccco....',
      '...ocssccccoo...',
      '...oopppppoo....',
      '....opppppo.....',
      '...oppooppo.....',
      '..oppo..oppo....',
      '.okkko..okkko...',
      '..ooo....ooo....',
    ], [
      '....ooccccoo....',
      '...occccCCco....',
      '...occccCCco....',
      '...occcccsso....',
      '...oopppppoo....',
      '....opppppo.....',
      '...oppooppo.....',
      '..oppo..oppo....',
      '.okkko..okkko...',
      '..ooo....ooo....',
    ]],
  },
  coat: {
    down: [[
      '..oowwccccwwoo..',
      '..oWwwccccwwWo..',
      '..oWwwccccwwWo..',
      '..osWwwccwwWso..',
      '..oWwwwwwwwwWo..',
      '..oWwwwwwwwwWo..',
      '...oWwppppwWo...',
      '...oopPooppoo...',
      '...okkkookkko...',
      '....ooo..ooo....',
    ], [
      '..oowwccccwwoo..',
      '..oWwwccccwwWo..',
      '..oswwccccwwWo..',
      '..oWWwwccwwWso..',
      '..oWwwwwwwwwWo..',
      '..oWwwwwwwwwWo..',
      '...oWwppppwWo...',
      '...oopPookkko...',
      '...okkko.ooo....',
      '....ooo.........',
    ], [
      '..oowwccccwwoo..',
      '..oWwwccccwwWo..',
      '..oWwwccccwwso..',
      '..oswwwccwwWWo..',
      '..oWwwwwwwwwWo..',
      '..oWwwwwwwwwWo..',
      '...oWwppppwWo...',
      '...okkkoopPoo...',
      '....ooo.okkko...',
      '.........ooo....',
    ]],
    left: [[
      '....oowcccoo....',
      '...owwwWWwwo....',
      '...owwwWWwwo....',
      '...owwwsswwo....',
      '...owwwwwwwo....',
      '...owwwwwwWo....',
      '....opppPo......',
      '....opppPo......',
      '...okkkkko......',
      '....oooooo......',
    ], [
      '....oowcccoo....',
      '...owwWWwwwo....',
      '...owwWWwwwo....',
      '...owsswwwwoo...',
      '...owwwwwwwo....',
      '...owwwwwwWo....',
      '...oppooppo.....',
      '..oppo..oppo....',
      '.okkko..okkko...',
      '..ooo....ooo....',
    ], [
      '....oowcccoo....',
      '...owwwwWWwo....',
      '...owwwwWWwo....',
      '...owwwwwsso....',
      '...owwwwwwwo....',
      '...owwwwwwWo....',
      '...oppooppo.....',
      '..oppo..oppo....',
      '.okkko..okkko...',
      '..ooo....ooo....',
    ]],
  },
  dress: {
    down: [[
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..oCccwwwwccCo..',
      '..osCcwwwwcCso..',
      '..oCcccccccccCo.',
      '.oCccccccccccCo.',
      '.oooooooooooooo.',
      '....osso.osso...',
      '...okkko.okkko..',
      '....ooo...ooo...',
    ], [
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..osccwwwwccCo..',
      '..oCCcwwwwccso..',
      '..oCcccccccccCo.',
      '.oCccccccccccCo.',
      '.oooooooooooooo.',
      '....osso.okkko..',
      '...okkko..ooo...',
      '....ooo.........',
    ], [
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..oCccwwwwccso..',
      '..osccwwwwcCCo..',
      '..oCcccccccccCo.',
      '.oCccccccccccCo.',
      '.oooooooooooooo.',
      '...okkko.osso...',
      '....ooo.okkko...',
      '.........ooo....',
    ]],
    left: [[
      '....ooccccoo....',
      '...occcCCcco....',
      '...ocwwCCcco....',
      '...ocwwsscco....',
      '...occcccccCo...',
      '..occcccccccCo..',
      '..oooooooooooo..',
      '.....osso.......',
      '....okkkko......',
      '.....ooooo......',
    ], [
      '....ooccccoo....',
      '...occCCccco....',
      '...ocwCCwcco....',
      '...ocsswwccoo...',
      '...occcccccCo...',
      '..occcccccccCo..',
      '..oooooooooooo..',
      '....oso..oso....',
      '...okkko.okkko..',
      '....ooo...ooo...',
    ], [
      '....ooccccoo....',
      '...occccCCco....',
      '...ocwwwCCco....',
      '...ocwwwcsso....',
      '...occcccccCo...',
      '..occcccccccCo..',
      '..oooooooooooo..',
      '....oso..oso....',
      '...okkko.okkko..',
      '....ooo...ooo...',
    ]],
  },
};

const SKIN = { s: '#f8d0a8', S: '#e0a078' };
const CHAR_BASE = { o: '#202028', e: '#202028', w: '#f8f8f8', W: '#b8b8c8', r: '#e84860' };

// Every person in the game.
const PEOPLE = {
  player: { head: 'cap', body: 'tee', pal: { a: '#e84040', A: '#a02828', h: '#403030', H: '#281c1c', c: '#3890e0', C: '#2060a8', p: '#404860', P: '#282c40', k: '#e04848' } },
  rival: { head: 'spiky', body: 'tee', pal: { h: '#c87830', H: '#8a4c18', c: '#8858c8', C: '#5c3898', p: '#6a5040', P: '#4a3428', k: '#383840' } },
  prof: { head: 'short', body: 'coat', pal: { h: '#c0c0c8', H: '#8a8a98', c: '#5890c0', C: '#38688a', p: '#7a5a40', P: '#5a4030', k: '#403838' } },
  mom: { head: 'long', body: 'dress', pal: { h: '#c85838', H: '#8a3420', c: '#f09098', C: '#c06070', k: '#a04848' } },
  nurse: { head: 'nurse', body: 'dress', pal: { h: '#f090b8', H: '#c06088', c: '#f8b8c8', C: '#d08098', k: '#f8f8f8' } },
  clerk: { head: 'short', body: 'tee', pal: { h: '#5a3828', H: '#3a2018', c: '#4878d0', C: '#3058a0', p: '#f0f0f0', P: '#c0c0c8', k: '#383840' } },
  aide: { head: 'short', body: 'coat', pal: { h: '#383840', H: '#202028', c: '#60a060', C: '#407840', p: '#404860', P: '#282c40', k: '#383840' } },
  girl: { head: 'long', body: 'dress', pal: { h: '#f0c848', H: '#b88a20', c: '#68b868', C: '#3c8a40', k: '#c05050' } },
  lass: { head: 'long', body: 'dress', pal: { h: '#6a4030', H: '#442418', c: '#e878a0', C: '#b04870', k: '#503848' } },
  boy: { head: 'short', body: 'tee', pal: { h: '#403030', H: '#281c1c', c: '#e8a030', C: '#b07018', p: '#4868c0', P: '#304890', k: '#383840' } },
  youngster: { head: 'cap', body: 'tee', pal: { a: '#3878e0', A: '#2050a8', h: '#8a5a30', H: '#5a3818', c: '#f8f8f8', C: '#b8b8c8', p: '#e0a040', P: '#a87020', k: '#383840' } },
  oldman: { head: 'bald', body: 'coat', pal: { h: '#d8d8e0', H: '#a0a0b0', c: '#8a6848', C: '#604830', w: '#b08860', W: '#806040', p: '#605048', P: '#403430', k: '#403838' } },
  woman: { head: 'long', body: 'dress', pal: { h: '#383050', H: '#201830', c: '#78a8e0', C: '#4a78b8', k: '#383840' } },
  man: { head: 'short', body: 'tee', pal: { h: '#8a5a30', H: '#5a3818', c: '#58a868', C: '#3a7848', p: '#6a5a50', P: '#4a3c34', k: '#383840' } },
  worker: { head: 'cap', body: 'tee', pal: { a: '#f8d030', A: '#c09818', h: '#403030', H: '#281c1c', c: '#f08030', C: '#b85818', p: '#4868a0', P: '#304870', k: '#503828' } },
  granny: { head: 'long', body: 'dress', pal: { h: '#d8d8e0', H: '#a0a0b0', c: '#9070b0', C: '#684888', k: '#503848' } },
  fisher: { head: 'cap', body: 'tee', pal: { a: '#608848', A: '#406030', h: '#584030', H: '#3a2818', c: '#c8b888', C: '#988858', p: '#506070', P: '#384450', k: '#383840' } },
};

// The AIMON BALL: blue top, white bottom, gold button.
const BALL_ROWS = [
  '....oooo....',
  '..oobbbboo..',
  '.obhhbbbbBo.',
  '.obhbbbbbBo.',
  'obbbbbbbbbBo',
  'oooooyyooooo',
  'owwwoyyowwwo',
  'owwwwoowwwgo',
  '.owwwwwwwgo.',
  '.owwwwwwggo.',
  '..oowgggoo..',
  '....oooo....',
];
const BALL_PAL = { o: '#202028', b: '#3878e0', B: '#2050a8', h: '#a0c8f8', w: '#f8f8f8', g: '#b8b8c8', y: '#f8d030' };

const Chars = {
  sheets: {},

  init() {
    for (const [id, person] of Object.entries(PEOPLE)) this.sheets[id] = this.build(person);
    this.emote = Pix.fromRows([
      '.oooooooooo.',
      'owwwwwwwwwwo',
      'owwwwrrwwwwo',
      'owwwwrrwwwwo',
      'owwwwrrwwwwo',
      'owwwwrrwwwwo',
      'owwwwwwwwwwo',
      'owwwwrrwwwwo',
      'owwwwwwwwwwo',
      '.ooooowwoooo',
      '.....owo....',
      '.....oo.....',
    ], { o: '#303038', w: '#f8f8f8', r: '#e03838' });
    this.ball = Pix.fromRows(BALL_ROWS, BALL_PAL);
    this.shadow = Pix.fromRows([
      '..oooooooooo..',
      'oooooooooooooo',
      '..oooooooooo..',
    ], { o: 'rgba(0,0,0,0.3)' });
  },

  build(person) {
    const head = HEADS[person.head];
    const body = BODIES[person.body];
    const pal = { ...CHAR_BASE, ...SKIN, ...person.pal };
    const frames = { down: [], up: [], left: [], right: [] };
    for (let f = 0; f < 3; f++) {
      frames.down.push(Pix.fromRows([...head.down, ...body.down[f]], pal));
      frames.up.push(Pix.fromRows([...head.up, ...(body.up || body.down)[f]], pal));
      const left = Pix.fromRows([...head.left, ...body.left[f]], pal);
      frames.left.push(left);
      frames.right.push(Pix.flipH(left));
    }
    return frames;
  },

  // walkPhase: 0 stand, 1 step A, 2 step B
  frame(id, dir, walkPhase) {
    return this.sheets[id][dir][walkPhase];
  },
};
