'use strict';
// Overworld people: 16x20 frames assembled from a head (hair style) and a
// body (outfit), then palette-swapped. Left-facing frames are mirrored for
// right. Frames per direction: stand, step A, step B.

const HEADS = {
  short: {
    down: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..ohhssssssHho..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....ohhhhhhoo...',
      '...ohhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..ohhsssssHhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  cap: {
    down: [
      '................',
      '.....oooooo.....',
      '....oaaaaaao....',
      '...oaaawwaaao...',
      '...oaaaaaaaaAo..',
      '..oAAAAAAAAAAo..',
      '..ohhssssssHho..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '....oaaaaaao....',
      '...oaaaaaaaao...',
      '...oaaaaaaaaAo..',
      '..oAaaaaaaaaAo..',
      '..ohAAAAAAAAho..',
      '..oHhhhhhhhhHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....oaaaaaao....',
      '...oaawaaaaao...',
      '...oaaaaaaaaAo..',
      '.oAAAAAAaaaaAo..',
      '..ohhssssshhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  spiky: {
    down: [
      '....o..o..o.....',
      '...oho.oho.o.o..',
      '..ohhhohhhohho..',
      '.ohhhhhhhhhhhho.',
      '..ohhhhhhhhhHo..',
      '.ohhhhhhhhhhhHo.',
      '..ohsshsssshHo..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '....o..o..o.....',
      '...oho.oho.o.o..',
      '..ohhhohhhohho..',
      '.ohhhhhhhhhhhho.',
      '..ohhhhhhhhhho..',
      '.ohhhhhhhhhhhHo.',
      '..ohhhhhhhhhHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '.......o..o.....',
      '..o...oho.oho...',
      '.ohoo.ohhhohhho.',
      '..ohhhhhhhhhhho.',
      '.ohhhhhhhhhhHo..',
      '..ohhhhhhhhhhHo.',
      '..ohsssssHhhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  long: {
    down: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '.ohhhhhhhhhhhHo.',
      '.ohhssssssssHHo.',
      '.ohsessssssesHo.',
      '.ohsessssssesHo.',
      '.ohhosssssSoHHo.',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '.ohhhhhhhhhhhHo.',
      '.ohhhhhhhhhhhHo.',
      '.ohhhhhhhhhhhHo.',
      '.ohhhhhhhhhhHHo.',
      '.oHhhhhhhhhhHHo.',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....ohhhhhhoo...',
      '...ohhhhhhhhho..',
      '..ohhhhhhhhhhHo.',
      '..ohhhhhhhhhhHo.',
      '..ohhsssssHhhHo.',
      '..osesssSshhHHo.',
      '..osesssSshhHHo.',
      '...ossssSohhHHo.',
    ],
  },
  nurse: {
    down: [
      '.....oooooo.....',
      '....owwwwwwo....',
      '...owwwrrwwwo...',
      '..ohowwwwwwohho.',
      '.ohhhoooooohhhho',
      '.ohhhhhhhhhhhHo.',
      '..ohhssssssHho..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '.....oooooo.....',
      '....owwwwwwo....',
      '...owwwwwwwwo...',
      '..ohowwwwwwohho.',
      '.ohhhoooooohhhho',
      '.ohhhhhhhhhhhHo.',
      '..ohhhhhhhhhHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '.....oooooo.....',
      '....owwwwwwo....',
      '...owrrwwwwwo...',
      '...owwwwwwwwohho',
      '..ohoooooooohhho',
      '..ohhhhhhhhhhHo.',
      '..ohhsssssHhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  bald: {
    down: [
      '................',
      '.....oooooo.....',
      '...oossssssoo...',
      '..osssssssssSo..',
      '..osssssssssSo..',
      '..ohsssssssshHo.',
      '..ohhoossoohHho.',
      '..ossessssesSo..',
      '..osshhhhhhsSo..',
      '...oshhhhhhSo...',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '...oossssssoo...',
      '..osssssssssSo..',
      '..osssssssssSo..',
      '..ohssssssssHo..',
      '..ohhssssssHHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....osssssSoo...',
      '...osssssssSSo..',
      '..osssssssssSo..',
      '..ossssssshhHo..',
      '..osoosssHhhHo..',
      '..osesssSshHHo..',
      '..oshhhhSshHo...',
      '...ohhhhSSHo....',
    ],
  },
  hood: {
    down: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..ohvvvvvvvvHo..',
      '..ohvVvvvvVvHo..',
      '..ohHsssssssHo..',
      '..oHHssssssHHo..',
      '...oHHssssHHo...',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..ohhhhhhhhhHo..',
      '..ohhhhhhhhhHo..',
      '..oHhhhhhhhhHo..',
      '..oHHhhhhhhHHo..',
      '...oHHHHHHHHo...',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....ohhhhhhoo...',
      '...ohhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..ovvvvhhhhhHo..',
      '..oVvvvhhhhhHo..',
      '..osssshhhhHHo..',
      '..osssHhhhHHo...',
      '...ossHHHHHo....',
    ],
  },
  band: {
    down: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhHo..',
      '..oaaaaaaaaaAo..',
      '..ohssssssssho..',
      '..ossessssesSo..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '................',
      '.....oooooo.....',
      '...oohhhhhhoo...',
      '..ohhhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..oaaaaaaaaaAo..',
      '..ohhhhhhhhhHo..',
      '..oHhhhhhhhHHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '................',
      '.....oooooo.....',
      '....ohhhhhhoo...',
      '...ohhhhhhhhho..',
      '..ohhhhhhhhhho..',
      '..oaaaaaaaaaAoa.',
      '..ohhsssssHhHo..',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
  hat: {
    down: [
      '................',
      '....oooooooo....',
      '...oaaaaaaaao...',
      '...oaaAAAAaao...',
      '.ooaaaaaaaaaaoo.',
      'oaaaaaaaaaaaaaao',
      '.oooohhhhhhoooo.',
      '..ossessssesso..',
      '..ossessssesSo..',
      '...osssssssSo...',
    ],
    up: [
      '................',
      '....oooooooo....',
      '...oaaaaaaaao...',
      '...oaaaaaaaao...',
      '.ooaaaaaaaaaaoo.',
      'oaaaaaaaaaaaaaao',
      '.oooohhhhhhoooo.',
      '..oHhhhhhhhhHo..',
      '..osHHHHHHHHso..',
      '....osssssso....',
    ],
    left: [
      '................',
      '.....oooooooo...',
      '....oaaaaaaaao..',
      '....oaaaaAAaao..',
      '..ooaaaaaaaaaaoo',
      '.oaaaaaaaaaaaaao',
      '..ooooshhhHoooo.',
      '..osesssSshHHo..',
      '..osesssSshHo...',
      '...ossssSSHo....',
    ],
  },
};


const BODIES = {
  tee: {
    down: [[
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..oCccccccccCo..',
      '..osCccccccCso..',
      '..oopppppppppoo.',
      '...opppppppPo...',
      '...oppPooppPo...',
      '...oppPooppPo...',
      '...okkkookkko...',
      '....ooo..ooo....',
    ], [
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..osccccccccCo..',
      '..oCCcccccccso..',
      '..oopppppppppoo.',
      '...opppppppPo...',
      '...oppPooppPo...',
      '...oppPookkko...',
      '...okkko.ooo....',
      '....ooo.........',
    ], [
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..oCccccccccso..',
      '..osccccccCCCo..',
      '..oopppppppppoo.',
      '...opppppppPo...',
      '...oppPooppPo...',
      '...okkkooppPo...',
      '....ooo.okkko...',
      '.........ooo....',
    ]],
    left: [[
      '....ooccccoo....',
      '...occcCCcco....',
      '...occcCCcco....',
      '...occcsscco....',
      '...oopppppoo....',
      '....opppppo.....',
      '....opppPo......',
      '....opppPo......',
      '...okkkkko......',
      '....oooooo......',
    ], [
      '....ooccccoo....',
      '...occCCccco....',
      '...occCCccco....',
      '...ocssccccoo...',
      '...oopppppoo....',
      '....opppppo.....',
      '...oppooppo.....',
      '..oppo..oppo....',
      '.okkko..okkko...',
      '..ooo....ooo....',
    ], [
      '....ooccccoo....',
      '...occccCCco....',
      '...occccCCco....',
      '...occcccsso....',
      '...oopppppoo....',
      '....opppppo.....',
      '...oppooppo.....',
      '..oppo..oppo....',
      '.okkko..okkko...',
      '..ooo....ooo....',
    ]],
  },
  coat: {
    down: [[
      '..oowwccccwwoo..',
      '..oWwwccccwwWo..',
      '..oWwwccccwwWo..',
      '..osWwwccwwWso..',
      '..oWwwwwwwwwWo..',
      '..oWwwwwwwwwWo..',
      '...oWwppppwWo...',
      '...oopPooppoo...',
      '...okkkookkko...',
      '....ooo..ooo....',
    ], [
      '..oowwccccwwoo..',
      '..oWwwccccwwWo..',
      '..oswwccccwwWo..',
      '..oWWwwccwwWso..',
      '..oWwwwwwwwwWo..',
      '..oWwwwwwwwwWo..',
      '...oWwppppwWo...',
      '...oopPookkko...',
      '...okkko.ooo....',
      '....ooo.........',
    ], [
      '..oowwccccwwoo..',
      '..oWwwccccwwWo..',
      '..oWwwccccwwso..',
      '..oswwwccwwWWo..',
      '..oWwwwwwwwwWo..',
      '..oWwwwwwwwwWo..',
      '...oWwppppwWo...',
      '...okkkoopPoo...',
      '....ooo.okkko...',
      '.........ooo....',
    ]],
    left: [[
      '....oowcccoo....',
      '...owwwWWwwo....',
      '...owwwWWwwo....',
      '...owwwsswwo....',
      '...owwwwwwwo....',
      '...owwwwwwWo....',
      '....opppPo......',
      '....opppPo......',
      '...okkkkko......',
      '....oooooo......',
    ], [
      '....oowcccoo....',
      '...owwWWwwwo....',
      '...owwWWwwwo....',
      '...owsswwwwoo...',
      '...owwwwwwwo....',
      '...owwwwwwWo....',
      '...oppooppo.....',
      '..oppo..oppo....',
      '.okkko..okkko...',
      '..ooo....ooo....',
    ], [
      '....oowcccoo....',
      '...owwwwWWwo....',
      '...owwwwWWwo....',
      '...owwwwwsso....',
      '...owwwwwwwo....',
      '...owwwwwwWo....',
      '...oppooppo.....',
      '..oppo..oppo....',
      '.okkko..okkko...',
      '..ooo....ooo....',
    ]],
  },
  dress: {
    down: [[
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..oCccwwwwccCo..',
      '..osCcwwwwcCso..',
      '..oCcccccccccCo.',
      '.oCccccccccccCo.',
      '.oooooooooooooo.',
      '....osso.osso...',
      '...okkko.okkko..',
      '....ooo...ooo...',
    ], [
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..osccwwwwccCo..',
      '..oCCcwwwwccso..',
      '..oCcccccccccCo.',
      '.oCccccccccccCo.',
      '.oooooooooooooo.',
      '....osso.okkko..',
      '...okkko..ooo...',
      '....ooo.........',
    ], [
      '..ooccccccccoo..',
      '..oCccccccccCo..',
      '..oCccwwwwccso..',
      '..osccwwwwcCCo..',
      '..oCcccccccccCo.',
      '.oCccccccccccCo.',
      '.oooooooooooooo.',
      '...okkko.osso...',
      '....ooo.okkko...',
      '.........ooo....',
    ]],
    left: [[
      '....ooccccoo....',
      '...occcCCcco....',
      '...ocwwCCcco....',
      '...ocwwsscco....',
      '...occcccccCo...',
      '..occcccccccCo..',
      '..oooooooooooo..',
      '.....osso.......',
      '....okkkko......',
      '.....ooooo......',
    ], [
      '....ooccccoo....',
      '...occCCccco....',
      '...ocwCCwcco....',
      '...ocsswwccoo...',
      '...occcccccCo...',
      '..occcccccccCo..',
      '..oooooooooooo..',
      '....oso..oso....',
      '...okkko.okkko..',
      '....ooo...ooo...',
    ], [
      '....ooccccoo....',
      '...occccCCco....',
      '...ocwwwCCco....',
      '...ocwwwcsso....',
      '...occcccccCo...',
      '..occcccccccCo..',
      '..oooooooooooo..',
      '....oso..oso....',
      '...okkko.okkko..',
      '....ooo...ooo...',
    ]],
  },
};

const SKIN = { s: '#f8d0a8', S: '#e0a078' };
const CHAR_BASE = { o: '#202028', e: '#202028', w: '#f8f8f8', W: '#b8b8c8', r: '#e84860' };

// Every person in the game.
const PEOPLE = {
  player: { head: 'cap', body: 'tee', pal: { a: '#e84040', A: '#a02828', h: '#403030', H: '#281c1c', c: '#3890e0', C: '#2060a8', p: '#404860', P: '#282c40', k: '#e04848' } },
  rival: { head: 'spiky', body: 'tee', pal: { h: '#c87830', H: '#8a4c18', c: '#8858c8', C: '#5c3898', p: '#6a5040', P: '#4a3428', k: '#383840' } },
  prof: { head: 'short', body: 'coat', pal: { h: '#c0c0c8', H: '#8a8a98', c: '#5890c0', C: '#38688a', p: '#7a5a40', P: '#5a4030', k: '#403838' } },
  mom: { head: 'long', body: 'dress', pal: { h: '#c85838', H: '#8a3420', c: '#f09098', C: '#c06070', k: '#a04848' } },
  nurse: { head: 'nurse', body: 'dress', pal: { h: '#f090b8', H: '#c06088', c: '#f8b8c8', C: '#d08098', k: '#f8f8f8' } },
  clerk: { head: 'short', body: 'tee', pal: { h: '#5a3828', H: '#3a2018', c: '#4878d0', C: '#3058a0', p: '#f0f0f0', P: '#c0c0c8', k: '#383840' } },
  aide: { head: 'short', body: 'coat', pal: { h: '#383840', H: '#202028', c: '#60a060', C: '#407840', p: '#404860', P: '#282c40', k: '#383840' } },
  girl: { head: 'long', body: 'dress', pal: { h: '#f0c848', H: '#b88a20', c: '#68b868', C: '#3c8a40', k: '#c05050' } },
  lass: { head: 'long', body: 'dress', pal: { h: '#6a4030', H: '#442418', c: '#e878a0', C: '#b04870', k: '#503848' } },
  boy: { head: 'short', body: 'tee', pal: { h: '#403030', H: '#281c1c', c: '#e8a030', C: '#b07018', p: '#4868c0', P: '#304890', k: '#383840' } },
  youngster: { head: 'cap', body: 'tee', pal: { a: '#3878e0', A: '#2050a8', h: '#8a5a30', H: '#5a3818', c: '#f8f8f8', C: '#b8b8c8', p: '#e0a040', P: '#a87020', k: '#383840' } },
  oldman: { head: 'bald', body: 'coat', pal: { h: '#d8d8e0', H: '#a0a0b0', c: '#8a6848', C: '#604830', w: '#b08860', W: '#806040', p: '#605048', P: '#403430', k: '#403838' } },
  woman: { head: 'long', body: 'dress', pal: { h: '#383050', H: '#201830', c: '#78a8e0', C: '#4a78b8', k: '#383840' } },
  man: { head: 'short', body: 'tee', pal: { h: '#8a5a30', H: '#5a3818', c: '#58a868', C: '#3a7848', p: '#6a5a50', P: '#4a3c34', k: '#383840' } },
  worker: { head: 'cap', body: 'tee', pal: { a: '#f8d030', A: '#c09818', h: '#403030', H: '#281c1c', c: '#f08030', C: '#b85818', p: '#4868a0', P: '#304870', k: '#503828' } },
  holt: { head: 'band', body: 'tee', pal: { s: '#b07848', S: '#8a5830', h: '#202020', H: '#101010', a: '#c8c0b8', A: '#908880', c: '#707888', C: '#4c5260', p: '#6a4a30', P: '#4a3220', k: '#383030' } },
  grunt: { head: 'hood', body: 'tee', pal: { h: '#383848', H: '#202028', v: '#a060e8', V: '#e0c0ff', c: '#303040', C: '#1c1c28', p: '#303040', P: '#1c1c28', k: '#8050c0' } },
  hiker: { head: 'hat', body: 'tee', pal: { a: '#8a6a40', A: '#6a4a28', h: '#5a3a20', H: '#3a2210', c: '#c87838', C: '#985020', p: '#6a5a40', P: '#4a3c28', k: '#503828' } },
  blackbelt: { head: 'band', body: 'tee', pal: { h: '#402818', H: '#28180c', a: '#303030', A: '#181818', c: '#f0f0f0', C: '#c0c0c8', p: '#f0f0f0', P: '#c0c0c8', k: '#e0c090' } },
  bugcatcher: { head: 'hat', body: 'tee', pal: { a: '#e8d080', A: '#b8a050', h: '#5a3a20', H: '#3a2210', c: '#78b848', C: '#4c8828', p: '#e0b048', P: '#a88020', k: '#503828' } },
  camper: { head: 'cap', body: 'tee', pal: { a: '#48884a', A: '#2c6030', h: '#6a4020', H: '#4a2810', c: '#d8a048', C: '#a87020', p: '#5a6a3a', P: '#3c4a24', k: '#503828' } },
  picnicker: { head: 'long', body: 'dress', pal: { h: '#c07838', H: '#8a4c18', c: '#78c078', C: '#4c9850', k: '#a05038' } },
  trainee: { head: 'short', body: 'tee', pal: { h: '#302018', H: '#1c1008', c: '#a8a098', C: '#7c746c', p: '#686058', P: '#48403a', k: '#383030' } },
  guard: { head: 'cap', body: 'tee', pal: { a: '#304070', A: '#1c2848', h: '#402818', H: '#28180c', c: '#4060a0', C: '#2c4478', p: '#283050', P: '#181c34', k: '#202028' } },
  historian: { head: 'bald', body: 'coat', pal: { h: '#e0e0e8', H: '#a8a8b8', c: '#6a5a88', C: '#4a3c68', w: '#8a7aa8', W: '#5c4c7c', p: '#4a4058', P: '#302a3c', k: '#302830' } },
  granny: { head: 'long', body: 'dress', pal: { h: '#d8d8e0', H: '#a0a0b0', c: '#9070b0', C: '#684888', k: '#503848' } },
  fisher: { head: 'cap', body: 'tee', pal: { a: '#608848', A: '#406030', h: '#584030', H: '#3a2818', c: '#c8b888', C: '#988858', p: '#506070', P: '#384450', k: '#383840' } },
  // Chapter 3
  ivy: { head: 'long', body: 'dress', pal: { h: '#4a8a3c', H: '#2c5c24', c: '#78b050', C: '#4c7c34', k: '#7a5a38' } },
  nerissa: { head: 'hat', body: 'coat', pal: { a: '#24386a', A: '#141e3c', h: '#2a9a9a', H: '#186a6a', c: '#f4f4f4', C: '#c8c8d0', w: '#24386a', W: '#141e3c', p: '#f0ece0', P: '#c8c0b0', k: '#2a2018' } },
  vesper: { head: 'long', body: 'coat', pal: { h: '#ded6f8', H: '#a898c8', c: '#a060e8', C: '#7038c0', w: '#2a2438', W: '#1a1624', p: '#1c1a24', P: '#100e16', k: '#383048' } },
  thane: { head: 'spiky', body: 'coat', pal: { h: '#302840', H: '#1c1628', c: '#f0c030', C: '#b08818', w: '#262634', W: '#16161e', p: '#1c1a24', P: '#100e16', k: '#383048' } },
  sailor: { head: 'cap', body: 'tee', pal: { a: '#f4f4f4', A: '#c0c0c8', h: '#402818', H: '#28180c', c: '#f4f4f4', C: '#3050a0', p: '#304880', P: '#1c2c58', k: '#383840' } },
  medium: { head: 'hood', body: 'dress', pal: { h: '#5a3c80', H: '#3c2458', v: '#5a3c80', V: '#8a6cb0', c: '#6a4a90', C: '#4a2c6c', k: '#302040' } },
  gardener: { head: 'hat', body: 'tee', pal: { a: '#e8c870', A: '#b89840', h: '#6a4020', H: '#4a2810', c: '#78a848', C: '#4c7c30', p: '#6a5a40', P: '#4a3c28', k: '#503828' } },
  swimmer: { head: 'long', body: 'dress', pal: { h: '#3868a8', H: '#204880', c: '#48a8e0', C: '#2878b0', k: '#f8d0a8' } },
  librarian: { head: 'long', body: 'dress', pal: { h: '#a8a8b8', H: '#787888', c: '#7a5a48', C: '#5a3c30', k: '#403030' } },
  admiral: { head: 'cap', body: 'coat', pal: { a: '#24386a', A: '#141e3c', h: '#d8d8e0', H: '#a0a0b0', c: '#f4f4f4', C: '#c8c8d0', w: '#24386a', W: '#141e3c', p: '#24386a', P: '#141e3c', k: '#202028' } },
};

// The AIMON BALL: blue top, white bottom, gold button.
const BALL_ROWS = [
  '....oooo....',
  '..oobbbboo..',
  '.obhhbbbbBo.',
  '.obhbbbbbBo.',
  'obbbbbbbbbBo',
  'oooooyyooooo',
  'owwwoyyowwwo',
  'owwwwoowwwgo',
  '.owwwwwwwgo.',
  '.owwwwwwggo.',
  '..oowgggoo..',
  '....oooo....',
];
const BALL_PAL = { o: '#202028', b: '#3878e0', B: '#2050a8', h: '#a0c8f8', w: '#f8f8f8', g: '#b8b8c8', y: '#f8d030' };

const Chars = {
  sheets: {},

  init() {
    for (const [id, person] of Object.entries(PEOPLE)) this.sheets[id] = this.build(person);
    this.emote = Pix.fromRows([
      '.oooooooooo.',
      'owwwwwwwwwwo',
      'owwwwrrwwwwo',
      'owwwwrrwwwwo',
      'owwwwrrwwwwo',
      'owwwwrrwwwwo',
      'owwwwwwwwwwo',
      'owwwwrrwwwwo',
      'owwwwwwwwwwo',
      '.ooooowwoooo',
      '.....owo....',
      '.....oo.....',
    ], { o: '#303038', w: '#f8f8f8', r: '#e03838' });
    this.ball = Pix.fromRows(BALL_ROWS, BALL_PAL);
    this.shadow = Pix.fromRows([
      '..oooooooooo..',
      'oooooooooooooo',
      '..oooooooooo..',
    ], { o: 'rgba(0,0,0,0.3)' });
  },

  build(person) {
    const head = HEADS[person.head];
    const body = BODIES[person.body];
    const pal = { ...CHAR_BASE, ...SKIN, ...person.pal };
    const frames = { down: [], up: [], left: [], right: [] };
    for (let f = 0; f < 3; f++) {
      frames.down.push(Pix.fromRows([...head.down, ...body.down[f]], pal));
      frames.up.push(Pix.fromRows([...head.up, ...(body.up || body.down)[f]], pal));
      const left = Pix.fromRows([...head.left, ...body.left[f]], pal);
      frames.left.push(left);
      frames.right.push(Pix.flipH(left));
    }
    return frames;
  },

  // walkPhase: 0 stand, 1 step A, 2 step B
  frame(id, dir, walkPhase) {
    return this.sheets[id][dir][walkPhase];
  },
};
